app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

Route::group(['namespace' => 'File'], function()
{
    Route::post('files/wisiwyg_upload}',
        ['as' => 'files.wisiwyg_upload', 'uses' => 'FilesController@wisiwyg_upload']
    );

    Route::get('images/{id}/resized/{size}/{crop?}',
        ['as' => 'images.resized', 'uses' => 'ImagesController@resize']
    );

    Route::resource('images', 'ImagesController', ['except' => ['destroy']]);
    Route::resource('files', 'FilesController', ['except' => ['destroy']]);
});


Route::get('admin', function () {
    return redirect('/admin/singe_pages/about');
});


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function()
{

    Route::resource('users', 'UsersController', ['except' => ['show', 'destroy']]);

    Route::get('contents/create/{category_id}', ['as' => 'admin.contents.create', 'uses' => 'ContentsController@create']);
    Route::get('contents/{category_id}', ['as' => 'admin.contents.index', 'uses' => 'ContentsController@index']);
    Route::resource('contents', 'ContentsController', ['except' => ['index', 'create']]);

    Route::get('singe_pages/{category_id}', [
        'as' => 'admin.single_pages',
        'uses' => 'SinglePagesController@edit'
    ])->where([
        'category_id'  => 'about|cooperation|contacts|programm'
    ]);
    Route::resource('single_pages', 'SinglePagesController', ['only' => ['store', 'update']]);


});


Route::get('/', 'WelcomeController@index');

Route::get('{single_pages_category}',
    ['as' => 'single_pages.show', 'uses' => 'SinglePagesController@show']
)->where([
    'single_pages_category' => 'about|cooperation|contacts|programm'
]);

Route::resource('contents', 'ContentsController', ['only' => ['show']]);
Route::resource('news', 'NewsController', ['only' => ['index', 'show']]);
Route::resource('galleries', 'GalleriesController', ['only' => ['index', 'show']]);

app/Models/Content.php
<?php

namespace App\Models;

use App\Lib\Models\Traits\LifeCycle;
use App\Lib\Models\Traits\HasXFCategoryMixin;
use App\Lib\Models\Traits\SeoableMixin;
//use App\Lib\Models\Traits\L12n\Separated as L12n;
use App\Lib\XFields\Category\ContentCategory as Category;

use App\Lib\Models\BaseXFModel;


class Content extends BaseXFModel
{
    const SLUG_FROM_FIELD = 'title';
    const CATEGORY_CLASS  = Category::class;

    use LifeCycle {
        LifeCycle::__construct as private __LifeCycleConstruct;
    }

    use SeoableMixin {
        SeoableMixin::__construct as private __SeoableConstruct;
    }

    use HasXFCategoryMixin;
//        L12n;

    protected $table = 'contents';

    protected $guarded = [];

    protected $casts = [
        'image_id'   => 'integer',
        'props'      => 'array',
    ];


    protected $attributes = [
        'is_visible' => true,
    ];


    protected $rules = array(
        'title'       => 'required',
        'category_id' => 'required|in:news,gallery,about,programm',
//        'desc'        => 'required',
    );



    public function scopeVisible($query) {
        $today = \Carbon\Carbon::today();
        return $query
            ->where('is_visible', true)
            ->where('publish_at', '<=', $today);
    }


    public function scopeForMainPage($query) {
        return $query->where('is_visible', true);
    }


    public function scopeFresh($query) {
        return $query->whereNotNull('publish_at')
            ->orderBy('publish_at', 'desc')
            ->orderBy('created_at', 'desc');
    }


    public function scopeUltraDate($query, $type, $date_field = 'created_at') {
        $obj = $query->whereNotNull($date_field)
            ->select($date_field)
            ->orderBy($date_field, ($type == 'min' ? 'desc' : 'asc'))
            ->first();

        if ($obj) {
            return \Carbon\Carbon::parse($obj->$date_field);
        }

        return null;
    }


    public function __construct($attributes = [])
    {
        $this->__LifeCycleConstruct();
        $this->__SeoableConstruct();
        parent::__construct($attributes);
    }


    public function xfields()
    {
        return $this->category->fields();
    }

}

app/Http/Controllers/Admin/ContentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Content;
use App\Lib\XFields\Category\ContentCategory;

use App\Http\Controllers\Admin\Traits\SpecialActions;

class ContentsController extends Controller
{
    use SpecialActions;

    const VIEWS_FOLDER = 'contents';
    const VIEW_VAR_NAME = 'content';

    public function index(Request $request)
    {
        $state       = $request->get('state', 'live');
        $category_id = $request->category_id; // x$category_id = $request->session()->get('content.category_id');

        $category = ContentCategory::find($category_id);
        $contents = Content::byState($state);

        if ($category_id) {
            $contents = $contents->byCategoryId($category_id);
        }

        $contents = $contents->fresh()->get();


        return view('admin.contents.index', [
            'contents'    => $contents,
            'categories'  => ContentCategory::all(),
            'category' => $category,
        ]);
    }

    public function create(Request $request, $category_id)
    {
        $content = new Content(['category_id' => $category_id]);
        return view('admin.contents.form', ['content' => $content]);
    }


    public function store(Request $request)
    {
        $content = new content($this->content_params());

        return $this->run_action( $content );
    }


    public function show($id)
    {
        //
    }


    public function edit(Request $request, $id)
    {
        $content = Content::find($id);
        return view('admin.contents.form', ['content' => $content]);
    }


    public function update(Request $request, $id)
    {

        $content = Content::find($id)
            ->fill($this->content_params());

        return $this->run_action( $content );
    }



    private function content_params()
    {
        return request()->content;
    }


}

app/Http/Controllers/ContentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Content;
use App\Lib\XFields\Category\ContentCategory;


class ContentsController extends Controller
{


    public function show(Request $request, $id)
    {
        $content = Content::live()->visible()
            ->bySlug($id)->first();

        return view('contents.show', [
            'content' => $content,
        ]);
    }

}

resources/views/admin/contents/form.blade.php
@extends('layouts.admin')

@section('content')

    <h1>
        {!! AdminContentCrumbs::items( ['content' => $content ] )->last()['title']  !!}
    </h1>

    {!! AdminContentCrumbs::show( ['content' => $content ] ) !!}


    <div class="row">

        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#info">Инфо</a></li>
            <li class=""><a data-toggle="tab" href="#seo">SEO</a></li>
        </ul>


        {!! Form::resource($content, ['route' => 'admin.contents', 'class' => 'form-horizontal']) !!}

        {!! Form::hidden('content[category_id]', $content->category_id) !!}

        <div class="tab-content">

            @include('admin.partials.errors', ['errors' => $content->errors()])

            @include("admin.contents.form._info_tab")
            @include("admin.partials.form.seoable_tab._simple", ['seoable' => $content, 'seoble_type' => 'content'])

        </div>

        @include("admin.partials.form._button_bar", ['object' => $content, 'lifecycled' => true])


        {!! Form::close() !!}

    </div>


@stop

resources/views/admin/contents/index.blade.php
@extends('layouts.admin')

@section('content_bar')

    {!! AdminFilterCell::show([
        //'category' => ['categories' => $categories],
        'lifecycle' => ['route' => 'admin.contents.index']
        ])
    !!}

@stop

@section('content')


    <div class="row">
        <?php

            $single_pages = [
                'about' => 'about',
                'programm' => 'programm',
            ];

        ?>

        @if ( array_has($single_pages, $category->id))
            {!! link_to_route('admin.single_pages', $category->title(), ['category_id' => $single_pages[$category->id]] ) !!}
        @endif
    </div>

    <div class="row">


        <h1>{!! $category->title('plural') !!}

            <div class="btn-group">
                {!! link_to_route('admin.contents.create', 'Добавить', ['category_id' => $category->id], ['class' => 'btn btn-primary']) !!}
            </div>

        </h1>

        @if ($contents->isEmpty())
            <p>Нет ни одного контента</p>

        @else

            <table class="table table-hover">
                <colgroup>
                    <col width="70%"/>
                </colgroup>
                <thead>
                    <tr>
                        <th>Заголовок</th>
                        <th>Тип</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($contents as $content)
                        <tr>

                            <td> {!! link_to_route('admin.contents.edit', $content->title, ['content_id' => $content->id]) !!} </td>
                            <td> {!! $content->category->title() !!} </td>

                        </tr>

                    @endforeach

                </tbody>
            </table>

        @endif

    </div>
@stop